AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  NewS3BucketTag:
    Type: String

Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-WebURL"

  WebsiteARN:
    Value: !GetAtt WebsiteBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-WebARN"

  WebsiteBucket:
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub "${AWS::StackName}-WebBucket"

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: WorkshopName
          Value: !Ref NewS3BucketTag
      WebsiteConfiguration:
        IndexDocument: index.html
