Description: Deploys ACMAutoValidate Lambda that can be used as a CFN Custom Resources.
Parameters:
  ParentStack:
    Type: String
    Default: awsworkshop
Outputs:
  FunctionArn:
    Export:
      Name: !Sub "${ParentStack}-ACMValidateFunction"
    Value:
      Fn::GetAtt:
        - ACMValidateFunction
        - Arn
Resources:
  ACMValidateFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: seibeast
        S3Key: 171d46fe88f3d2c77fa585f6db9cbfd0
      FunctionName: !Sub "${ParentStack}-ACMValidateFunction"
      Handler: acm_autovalidate.handler
      Role:
        Fn::GetAtt:
          - ACMValidateRole
          - Arn
      Runtime: python3.6

  ACMValidateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - acm:DescribeCertificate
                  - acm:ListCertificates
                  - acm:RequestCertificate
                  - acm:DeleteCertificate
                  - route53:ListHostedZonesByName
                  - route53:ChangeResourceRecordSets
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: !Sub "${ParentStack}-ACMandRoute53Access"
